version: "3.8"
services:
  local:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: angel-algo-streamlit
    env_file:
      - .env
    command: ["streamlit", "run", "main.py"]
    ports:
      - "8501:8501"
    volumes:
      - ./:/app/
    restart: always
